### ISSUE TITLE
Inlcude md from other extension ?

### ISSUE THREAD

**Issue by Gitsko** [georgringer/doc#9]
It is possible to start a README from a different ext. I have a link in the sitebar.md `[other Ext](../../../other_ext/README.md)` but unfortunately only a 404 is output.

is there a way to include them directly?

**Comment by georgringer** [comment]
this is not possible and don't plan to extend the extension to be an umbrella ext rendering documentation which comes from several extensions. if you need that you could check if symlinks would be possible
